#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

postProcessing/Allwmake $*

# ----------------------------------------------------------------- end-of-file
